# Generated by Django 4.0.2 on 2022-02-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='divisions',
            field=models.ManyToManyField(to='main_app.Division'),
        ),
    ]
