# Generated by Django 4.0.2 on 2022-02-23 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_player_divisions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='division',
            old_name='roster_size',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='division',
            old_name='year',
            new_name='name',
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Stat Date')),
                ('stat', models.CharField(choices=[('G', 'Goal'), ('A', 'Assist'), ('B', 'Block')], default='G', max_length=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.player')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
