# Generated by Django 4.0.2 on 2022-02-23 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_player_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
    ]
